name: publish
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        type: "string"
        required: true
        description: "The existing tag to publish to FlakeHub"
		
jobs:
  check-flake:
    uses: ./.github/workflows/flake-check.yml
    
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          tag: "${{ inputs.tag }}"
          name: "Memonia/dockerComposeFlake"
          visibility: "public"
          include-output-paths: true
